# include: 
#   - authentik.yaml

services:
  demoapi:
    build:
      context: ./DemoAPI
      dockerfile: Dockerfile
    container_name: demoapi
    environment:
      - TZ=America/Montevideo   
      - PORT=8000               
      - DEBUG=True               
    ports:
      - "8000:8000"              
    volumes:
      - ./DemoAPI:/app         
    networks:
      - web
    restart: unless-stopped

  duckdns:
    image: linuxserver/duckdns:version-bdcb41e5
    container_name: duckdns
    environment:
      - TZ=America/Montevideo
      - SUBDOMAINS=demoucu
      - TOKEN=${TOKEN_DUCKDNS}
      - LOG_FILE=true
      - UPDATE_IP=ipv4
    env_file:
      - .env
    restart: unless-stopped

    
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

networks:
  web:


volumes:
  caddy_data:
  caddy_config:


